# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sortowanie.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(831, 674)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(751, 590))
        MainWindow.setMaximumSize(QtCore.QSize(1920, 1080))
        MainWindow.setWindowOpacity(4.0)
        MainWindow.setAutoFillBackground(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 2, 5, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setFrameShape(QtWidgets.QFrame.Box)
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 3, 4, 3, 4)
        self.label_load = QtWidgets.QLabel(self.centralwidget)
        self.label_load.setText("")
        self.label_load.setWordWrap(True)
        self.label_load.setObjectName("label_load")
        self.gridLayout.addWidget(self.label_load, 0, 1, 3, 3)
        self.pushButton_load = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_load.setObjectName("pushButton_load")
        self.gridLayout.addWidget(self.pushButton_load, 0, 0, 2, 1)
        self.label_item_edited = QtWidgets.QLabel(self.centralwidget)
        self.label_item_edited.setObjectName("label_item_edited")
        self.gridLayout.addWidget(self.label_item_edited, 0, 6, 1, 1)
        self.pushButton_save_as = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_save_as.setObjectName("pushButton_save_as")
        self.gridLayout.addWidget(self.pushButton_save_as, 2, 4, 1, 1)
        self.pushButton_save = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_save.setCheckable(False)
        self.pushButton_save.setObjectName("pushButton_save")
        self.gridLayout.addWidget(self.pushButton_save, 0, 4, 2, 1)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 0, 5, 1, 1)
        self.label_right = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.label_right.sizePolicy().hasHeightForWidth())
        self.label_right.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(26)
        self.label_right.setFont(font)
        self.label_right.setFrameShape(QtWidgets.QFrame.Box)
        self.label_right.setText("")
        self.label_right.setTextFormat(QtCore.Qt.PlainText)
        self.label_right.setScaledContents(True)
        self.label_right.setWordWrap(True)
        self.label_right.setObjectName("label_right")
        self.gridLayout.addWidget(self.label_right, 6, 4, 1, 4)
        self.label_item_all = QtWidgets.QLabel(self.centralwidget)
        self.label_item_all.setObjectName("label_item_all")
        self.gridLayout.addWidget(self.label_item_all, 1, 6, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 5, 1, 1)
        self.pushButton_reload = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_reload.setObjectName("pushButton_reload")
        self.gridLayout.addWidget(self.pushButton_reload, 2, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setFrameShape(QtWidgets.QFrame.Box)
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 3, 0, 3, 4)
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout.addWidget(self.progressBar, 2, 6, 1, 2)
        self.label_left = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.label_left.sizePolicy().hasHeightForWidth())
        self.label_left.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(26)
        self.label_left.setFont(font)
        self.label_left.setAutoFillBackground(False)
        self.label_left.setFrameShape(QtWidgets.QFrame.Box)
        self.label_left.setText("")
        self.label_left.setTextFormat(QtCore.Qt.PlainText)
        self.label_left.setScaledContents(True)
        self.label_left.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_left.setWordWrap(True)
        self.label_left.setObjectName("label_left")
        self.gridLayout.addWidget(self.label_left, 6, 0, 1, 4)
        self.toolButton_draw = QtWidgets.QToolButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.toolButton_draw.sizePolicy().hasHeightForWidth())
        self.toolButton_draw.setSizePolicy(sizePolicy)
        self.toolButton_draw.setObjectName("toolButton_draw")
        self.gridLayout.addWidget(self.toolButton_draw, 9, 3, 1, 2)
        self.toolButton_left = QtWidgets.QToolButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.toolButton_left.sizePolicy().hasHeightForWidth())
        self.toolButton_left.setSizePolicy(sizePolicy)
        self.toolButton_left.setObjectName("toolButton_left")
        self.gridLayout.addWidget(self.toolButton_left, 9, 0, 1, 3)
        self.toolButton_right = QtWidgets.QToolButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.toolButton_right.sizePolicy().hasHeightForWidth())
        self.toolButton_right.setSizePolicy(sizePolicy)
        self.toolButton_right.setObjectName("toolButton_right")
        self.gridLayout.addWidget(self.toolButton_right, 9, 5, 1, 3)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.label_right.raise_()
        self.label_left.raise_()
        self.pushButton_load.raise_()
        self.pushButton_save.raise_()
        self.progressBar.raise_()
        self.label.raise_()
        self.pushButton_save_as.raise_()
        self.label_4.raise_()
        self.label_5.raise_()
        self.label_item_edited.raise_()
        self.label_item_all.raise_()
        self.pushButton_reload.raise_()
        self.label_load.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Sortowanie obiektów"))
        self.label.setText(_translate("MainWindow", "Posortowane:"))
        self.pushButton_load.setText(_translate("MainWindow", "Załaduj sortowanie z pliku..."))
        self.label_item_edited.setText(_translate("MainWindow", "-"))
        self.pushButton_save_as.setText(_translate("MainWindow", "Zapisz zmiany jako..."))
        self.pushButton_save.setText(_translate("MainWindow", "Zapisz zmiany"))
        self.label_5.setText(_translate("MainWindow", "Zmienione:"))
        self.label_item_all.setText(_translate("MainWindow", "-"))
        self.label_4.setText(_translate("MainWindow", "Wszystkich:"))
        self.pushButton_reload.setText(_translate("MainWindow", "Przeładuj"))
        self.toolButton_draw.setText(_translate("MainWindow", "Remis (w, ↓)"))
        self.toolButton_draw.setShortcut(_translate("MainWindow", "W, Down"))
        self.toolButton_left.setText(_translate("MainWindow", "Lewy (q, ←)"))
        self.toolButton_left.setShortcut(_translate("MainWindow", "Q, Left"))
        self.toolButton_right.setText(_translate("MainWindow", "Prawy (e, →)"))
        self.toolButton_right.setShortcut(_translate("MainWindow", "E, Right"))

